name: CI Back-end

on:
  push:
    branches:
      - 'main'
    paths:
      - 'back-end/**'
  pull_request:
    paths:
      - 'back-end/**'
  workflow_call:
  
jobs:
  primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Compilação / Test / Package
        working-directory: back-end/
        run: mvn --activate-profiles prod test
        
  segundo-job:
    runs-on: ubuntu-latest
    needs: [primeiro-job]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Compilação / Test / Package
        working-directory: back-end/
        run: mvn --activate-profiles prod -DskipTests package
